### ISSUE TITLE
Can't detect unidentified or untrained faces

### ISSUE THREAD

**Issue by sathyasun** [JeeveshN/Facial-Recognition-Tool#8]
I've recently started using your code to do some face recognition. It works great. I had to do some changes to bring it up to date but it works fine. One problem I'm having with is that it can't detect faces that it hasn't been trained on. From my observation, if it is trained on one face, it recognises all faces as the one face. Do you have any clue as to why this may be?

**Comment by JeeveshN** [comment]
@sathyasun so with every prediction it also gives a confidence value, at the time of writing this I did not put a threshold on it. So when you train it on only one face it predicts that all the other faces are also the same face but with a very high confidence value.
Put a threshold on this value and you'll get the results you want.

**Comment by JeeveshN** [comment]
https://github.com/JeeveshN/Facial-Recognition-Tool/blob/7ccaed326111f81c5e642c2707d62de388bd1dcd/face_recog.py#L91
The conf variable.

**Comment by sathyasun** [comment]
@JeeveshN Thanks! I'll work on this and let you know how it ends up.
